const fs = require('fs');
const path = require('path');
const os = require('os');
const ROOT = path.join(__dirname, '..');
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'planner-'));

let app = fs.readFileSync(ROOT + '/js/app.js', 'utf8');

// ---- structural / calendar replacements (English uses Gregorian, Sunday-first) ----
app = app.replace(/var MONTHS = \[[^\]]*\];/, "var MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];");
app = app.replace(/var WEEKDAYS = \[[^\]]*\];/, "var WEEKDAYS = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];");
app = app.replace(/var FA = \[[^\]]*\];/, "var FA = ['0','1','2','3','4','5','6','7','8','9'];");
app = app.replace("function weekdayIdx(k) { return (fromKey(k).getDay() + 1) % 7; }", "function weekdayIdx(k) { return fromKey(k).getDay(); }");
app = app.replace("function faNum(n) { return String(n).replace(/[0-9]/g, function (d) { return FA[+d]; }); }", "function faNum(n) { return String(n); }");
// keep the same storage key as the Persian app so data is shared between languages

// ---- translation dictionary (Persian -> English), longest keys first ----
const DIC = [
  ['کار عقب‌مانده‌ای نیست. آفرین!', 'No overdue tasks. Well done!'],
  ['برای امروز کاری ثبت نشده — یک کار جدید بساز.', 'No tasks for today — create one.'],
  ['برای نمایش نمودار حداقل دو اندازه ثبت کن.', 'Add at least two measurements to see the chart.'],
  ['اهداف کوتاه‌مدت، بلندمدت و ماهانه را تعریف کن', 'Define short, long and monthly goals'],
  ['بر اساس مدت‌زمان کارهای تیک‌خورده', 'Based on completed tasks'],
  ['رنگ و حال‌وهوای پلنر را انتخاب کن', 'Pick your color mood'],
  ['از تصاویر پلنر به‌عنوان پس‌زمینه استفاده کن', 'Use planner images as background'],
  ['استریک، نرخ موفقیت و زنجیره‌ها', 'Streaks, success rate and chains'],
  ['برای برنامه‌های ثابت هفته (مثل کلاس‌ها)', 'For fixed weekly plans (e.g. classes)'],
  ['خروجی، ورودی و بازنشانی', 'Export, import & reset'],
  ['دسته‌بندی‌ها و زیردسته‌ها', 'Categories & subcategories'],
  ['تاریخچه و ژورنال‌ها', 'History & journals'],
  ['داده نمونه جایگزین شود؟', 'Replace with demo data?'],
  ['همه داده‌ها پاک شود؟', 'Delete all data?'],
  ['این کار حذف شود؟', 'Delete this task?'],
  ['این هدف حذف شود؟', 'Delete this goal?'],
  ['این دسته حذف شود؟', 'Delete this category?'],
  ['حداقل یک روز هفته را انتخاب کن.', 'Select at least one weekday.'],
  ['عنوان کار را وارد کن.', 'Enter a task title.'],
  ['عنوان هدف را وارد کن.', 'Enter a goal title.'],
  ['نتیجه‌ای پیدا نشد.', 'No results found.'],
  ['فایل نامعتبر است.', 'Invalid file.'],
  ['برای امروز کاری ثبت نشده', 'No tasks for today'],
  ['کارهای عقب‌مانده هفته‌های قبل', 'Overdue from previous weeks'],
  ['روزهای فعال', 'Active days'],
  ['ساعت کل کار', 'Total hours'],
  ['میانگین خواب', 'Avg sleep'],
  ['میانگین روزانه', 'Daily average'],
  ['امتیاز XP', 'XP points'],
  ['امتیاز کل', 'Total XP'],
  ['امتیاز (۰ تا ۵)', 'Rating (0-5)'],
  ['کارهای انجام‌شده', 'Completed tasks'],
  ['کارهای هفتگی این هفته', 'Weekly tasks'],
  ['کارهای این روز', 'Tasks for this day'],
  ['کار امروز (ساعت:دقیقه)', 'Today’s work (h:mm)'],
  ['کار جدید', 'New task'],
  ['روز فعال', 'Active days'],
  ['روز کار', 'Work days'],
  ['روز مانده', 'days left'],
  ['روز گذشته', 'days ago'],
  ['هفته ', 'Week '],
  [' هفته', ' week'],
  ['هفته', 'Week'],
  ['این هفته', 'this week'],
  ['ماه بعد: ', 'Next month: '],
  ['روند ۶ ماه', '6-month trend'],
  ['خلاصه ماه', 'Month summary'],
  ['ذخیره خلاصه ماه', 'Save month summary'],
  ['بهترین اتفاق ماه', 'Best of the month'],
  ['مهم‌ترین دستاورد', 'Top achievement'],
  ['کارهایی که ماه بعد انجام می‌دهم', 'Tasks for next month'],
  ['در این ماه کاری تیک نخورده.', 'Nothing completed this month.'],
  ['ماهانه', 'Monthly'],
  ['ماه', 'Month'],
  ['سال', 'Year'],
  ['ساعت‌های کار و شغل', 'Work hours'],
  ['ساعت خواب', 'Sleep hours'],
  ['ساعت', 'Time'],
  ['نمودار خواب ۱۴ روز اخیر', 'Sleep — last 14 days'],
  ['استریک عادت‌ها', 'Habit streaks'],
  ['استریک نمایش‌داده‌شده در داشبورد', 'Dashboard streak'],
  ['استریک فعلی', 'Current streak'],
  ['استریک ', 'Streak '],
  ['نرخ موفقیت', 'Success rate'],
  ['کل روزها', 'Total days'],
  ['کل هزینه', 'Total expense'],
  ['کل', 'Total'],
  ['تفکیک ریزپروژه‌ها', 'Breakdown'],
  ['آمار کلی', 'Overall stats'],
  ['آمار', 'Stats'],
  ['هیت‌مپ هفته', 'Week heatmap'],
  ['میزان تحقق برنامه‌ریزی', 'Plan completion'],
  ['پیشرفت اهداف', 'Goals progress'],
  ['پیشرفت', 'Progress'],
  ['هنوز هدفی نساخته‌ای', 'No goals yet'],
  ['هنوز هدفی ثبت نشده.', 'No goals yet.'],
  ['هدف جدید', 'New goal'],
  ['عنوان هدف', 'Goal title'],
  ['ویرایش هدف', 'Edit goal'],
  ['ساخت هدف', 'Create goal'],
  ['کوتاه‌مدت', 'Short-term'],
  ['بلندمدت', 'Long-term'],
  ['مدت (دقیقه)', 'Duration (min)'],
  ['مدت', 'Term'],
  ['ددلاین', 'Deadline'],
  ['بدون ددلاین', 'No deadline'],
  ['کتاب، پادکست و فیلم', 'Books, podcasts and movies'],
  ['نویسنده / سازنده', 'Author / Creator'],
  ['افزودن به کتابخانه', 'Add to library'],
  ['کتابخانه', 'Library'],
  ['پادکست', 'Podcast'],
  ['کتاب', 'Book'],
  ['فیلم', 'Movie'],
  ['خوانده‌شده', 'Finished'],
  ['در حال خواندن', 'Reading'],
  ['می‌خواهم', 'Want to'],
  ['وضعیت', 'Status'],
  ['یادداشت‌های روزانه', 'Daily notes'],
  ['یادداشت روزانه و ژورنال', 'Daily notes & journal'],
  ['یادداشت / رویداد این روز', 'Note / event for this day'],
  ['ژورنال پایان هفته', 'End-of-week journal'],
  ['ژورنال‌های هفتگی', 'Weekly journals'],
  ['ژورنال هفتگی ثبت نشده.', 'No weekly journal.'],
  ['ذخیره ژورنال', 'Save journal'],
  ['خلاصه‌های ماهانه', 'Monthly summaries'],
  ['خلاصه ماهانه‌ای ثبت نشده.', 'No monthly summary.'],
  ['خلاصه این هفته بر اساس دسته', 'This week by category'],
  ['خلاصه', 'Summary'],
  ['بهترین اتفاق: ', 'Best: '],
  ['دستاورد: ', 'Achievement: '],
  ['مسیر پیشرفت', 'Progress path'],
  ['گاه‌شمار اهداف تا رسیدن به مقصد', 'Goal timeline to destination'],
  ['گیمیفیکیشن XP', 'XP gamification'],
  ['با انجام کارها امتیاز بگیر و به هدف برس', 'Earn points and reach your goal'],
  ['برای کارها امتیاز XP تعیین کن.', 'Set XP for your tasks.'],
  ['درآمد، هزینه، بودجه و قرض‌ها', 'Income, expenses, budget and debts'],
  ['درآمد و خرج', 'Income & Expense'],
  ['سهم دسته‌ها از هزینه', 'Expense by category'],
  ['هزینه‌ای ثبت نشده.', 'No expenses.'],
  ['بودجه‌بندی ماهانه', 'Monthly budget'],
  ['بودجه‌ای تعیین نشده.', 'No budget set.'],
  ['بودجه جدید', 'New budget'],
  ['بودجه‌بندی', 'Budget'],
  ['مبلغ بودجه', 'Budget amount'],
  ['بیشتر از بودجه خرج کردی!', 'Over budget!'],
  ['تراکنش جدید', 'New transaction'],
  ['تراکنشی ثبت نشده.', 'No transactions.'],
  ['تراکنش‌ها', 'Transactions'],
  ['قرضی ثبت نشده.', 'No loans.'],
  ['قرض جدید', 'New loan'],
  ['قرض دادم', 'Lent'],
  ['قرض گرفتم', 'Borrowed'],
  ['قرض‌ها', 'Debts'],
  ['درآمد', 'Income'],
  ['هزینه', 'Expense'],
  ['باقی‌مانده از ', 'remaining of '],
  ['باقی‌مانده', 'Remaining'],
  ['بدهی', 'Debt'],
  ['حساب جدید', 'New account'],
  ['نام حساب', 'Account name'],
  ['حساب‌ها', 'Accounts'],
  ['حساب اصلی', 'Main account'],
  ['حساب', 'Account'],
  ['طرف حساب', 'Person'],
  ['پرداخت‌شده', 'Paid'],
  ['پرداخت کامل', 'Full payment'],
  ['سررسید', 'Due'],
  ['تکرار ماهانه', 'Monthly repeat'],
  ['هر ماه', 'monthly'],
  ['مبلغ', 'Amount'],
  ['بله', 'Yes'],
  ['خیر', 'No'],
  ['مثلاً خوراکی', 'e.g. Groceries'],
  ['مثلاً رضا', 'e.g. Reza'],
  ['مثلاً کنکور', 'e.g. University exam'],
  ['مثلاً یاسمن', 'e.g. Yasmin'],
  ['مثلاً ۱۸:۰۰', 'e.g. 18:00'],
  ['مثلاً کلاس زبان', 'e.g. Language class'],
  ['مثلاً قبولی در آزمون زبان', 'e.g. Pass the language exam'],
  ['مثلاً', 'e.g. '],
  ['ردیف جدید', 'New row'],
  ['برنامه هفتگی', 'Schedule'],
  ['تنظیمات', 'Settings'],
  ['شخصی‌سازی پلنر', 'Customize your planner'],
  ['نام شما', 'Your name'],
  ['تم پلنر', 'Planner theme'],
  ['استایل پلنر', 'Planner style'],
  ['حالت نمایش کارت‌ها و فشردگی', 'Card layout & density'],
  ['تصویر پس‌زمینه', 'Background image'],
  ['بدون تصویر', 'No background'],
  ['پایه ساختار پلنر', 'Planner structure'],
  ['افزودن زیردسته', 'Add subcategory'],
  ['دسته جدید', 'New category'],
  ['افزودن دسته', 'Add category'],
  ['داده‌ها', 'Data'],
  ['خروجی JSON', 'Export JSON'],
  ['ورود از فایل', 'Import from file'],
  ['بارگذاری داده نمونه', 'Load demo data'],
  ['بازنشانی کامل', 'Full reset'],
  ['گالری تصاویر پلنر', 'Planner gallery'],
  ['دور کمر', 'Waist'],
  ['دور سینه', 'Chest'],
  ['دور باسن', 'Hip'],
  ['وزن (kg)', 'Weight (kg)'],
  ['وزن و سایز', 'Weight & size'],
  ['روند تغییرات بدنی', 'Body trend'],
  ['تاریخچه اندازه‌ها', 'Measurement history'],
  ['آخرین اندازه‌ها', 'Latest measurements'],
  ['ثبت اندازه‌ها', 'Log measurements'],
  ['ثبت اندازه', 'Log measurement'],
  ['هنوز اندازه‌ای ثبت نشده.', 'No measurements yet.'],
  ['بدن', 'Body'],
  ['وزن', 'Weight'],
  ['تغییر', 'Change'],
  ['یادآورها و کارهای امروز', 'Reminders & today’s tasks'],
  ['یادآور جدید', 'New reminder'],
  ['یادآوری ثبت نشده.', 'No reminders yet.'],
  ['متن یادآور', 'Reminder text'],
  ['یادآورها', 'Reminders'],
  ['کار جدید', 'New task'],
  ['انجام شده', 'completed'],
  ['ویرایش کار', 'Edit task'],
  ['عنوان کار', 'Task title'],
  ['توزیع ماهانه کارها', 'Tasks this month'],
  ['توزیع کارها بر اساس دسته', 'Tasks by category'],
  ['کاری برای این روز نیست.', 'No tasks for this day.'],
  ['کاری در این هفته نیست.', 'No tasks this week.'],
  ['انتقال به این هفته', 'Move to this week'],
  ['نمای هفته', 'Week view'],
  ['هنوز کاری تیک نخورده.', 'No tasks completed yet.'],
  ['برو به امروز', 'Go to today'],
  ['امروز', 'Today'],
  ['هفته', 'Week'],
  ['اهداف', 'Goals'],
  ['عادات', 'Habits'],
  ['عادت‌ها', 'Habits'],
  ['عادت جدید', 'New habit'],
  ['عنوان عادت', 'Habit title'],
  ['افزودن عادت', 'Add habit'],
  ['هنوز عادتی نساخته‌ای.', 'No habits yet.'],
  ['نمای ماه — ', 'Month view — '],
  ['چرخه بانوان', 'Cycle (women)'],
  ['شروع آخرین چرخه', 'Last cycle start'],
  ['طول دوره (روز)', 'Cycle length (days)'],
  ['علائم', 'Symptoms'],
  ['چرخه ', 'Cycle '],
  [' روزه — شروع: ', ' days — start: '],
  ['یادداشت‌ها', 'Notes'],
  ['یادداشت جدید', 'New note'],
  ['یادداشتی ثبت نشده.', 'No notes yet.'],
  ['یادداشت', 'Notes'],
  ['ایده‌های پروژه پلنر', 'Planner project ideas'],
  ['ایده‌ها', 'Ideas'],
  ['عادت‌های اتمی', 'Atomic Habits'],
  ['جیمز کلیر', 'James Clear'],
  ['کتاب فوق‌العاده برای ساختن عادت', 'A great book for building habits'],
  ['قبولی در آزمون آیلتس', 'Pass the IELTS exam'],
  ['رسیدن به نمره ۷ در آزمون آیلتس', 'Score 7 in IELTS'],
  ['تمرین روزانه ریدینگ', 'Daily reading practice'],
  ['مکالمه ۳۰ دقیقه‌ای', '30-min speaking'],
  ['پادکست روزانه', 'Daily podcast'],
  ['راه‌اندازی پروژه شخصی', 'Launch personal project'],
  ['طراحی صفحه اصلی', 'Design homepage'],
  ['نوشتن مستندات', 'Write documentation'],
  ['جلسه تیم', 'Team meeting'],
  ['بررسی ایمیل‌ها', 'Check emails'],
  ['پروژه طراحی', 'Design project'],
  ['کلاس زبان', 'Language class'],
  ['تمرین ریدینگ', 'Reading practice'],
  ['تماس با خانواده', 'Call family'],
  ['نوشیدن آب', 'Drink water'],
  ['گرفتن لباس از خشکشویی', 'Pick up laundry'],
  ['امروز پرانرژی بودم.', 'I felt energetic today.'],
  ['خرید خوراکی', 'Buy groceries'],
  ['حمل و نقل', 'Transport'],
  ['قرض ماشین', 'Car loan'],
  ['حقوق', 'Salary'],
  ['خوراکی', 'Groceries'],
  ['کار و شغل', 'Work & Job'],
  ['جلسه‌ها', 'Meetings'],
  ['پروژه‌ها', 'Projects'],
  ['ایمیل و پیگیری', 'Email & Follow-up'],
  ['یادگیری', 'Learning'],
  ['مهارت تازه', 'New Skill'],
  ['روزانه', 'Daily'],
  ['مطالعه شبانه', 'Night Study'],
  ['ورزش', 'Exercise'],
  ['شخصی', 'Personal'],
  ['خانواده', 'Family'],
  ['تفریح', 'Fun'],
  ['رژیم', 'Diet'],
  ['سلامتی', 'Health'],
  ['بدون دسته', 'Uncategorized'],
  ['سایر', 'Other'],
  ['شرح', 'Description'],
  ['زیاد', 'High'],
  ['کم', 'Low'],
  ['متوسط', 'Medium'],
  ['پروژه‌ها', 'Projects'],
  ['توضیحات', 'Description'],
  ['دسته‌بندی', 'Category'],
  ['زیردسته', 'Subcategory'],
  ['اولویت', 'Priority'],
  ['تکرار', 'Repeat'],
  ['فقط این هفته', 'This week only'],
  ['روتین دائمی', 'Permanent routine'],
  ['روز انجام', 'Day'],
  ['آزاد (هر روز این هفته)', 'Any day (this week)'],
  ['آزاد (هر روز هفته)', 'Any day'],
  ['روزهای هفته', 'Weekdays'],
  ['انصراف', 'Cancel'],
  ['ذخیره', 'Save'],
  ['بستن', 'Close'],
  ['عنوان هدف', 'Goal title'],
  ['عنوان', 'Title'],
  ['تاریخ', 'Date'],
  ['متن', 'Text'],
  ['دسته', 'Category'],
  ['رنگ', 'Color'],
  ['نوع', 'Type'],
  ['همه', 'All'],
  ['هدف: ', 'Goal: '],
  ['کار', 'Task'],
  ['هدف', 'Goal'],
  ['عادت', 'Habit'],
  ['رز', 'Rose'],
  ['آب', 'Water'],
  ['مسیر', 'Path'],
  ['مالی', 'Finance'],
  ['پلنر تخصصی', 'Professional Planner'],
  ['نسخه آفلاین — همه‌چیز را امتحان کن', 'Offline version — try everything'],
  ['جستجو...', 'Search...'],
  ['کلاسیک', 'Classic'],
  ['مینیمال', 'Minimal'],
  ['شیشه‌ای', 'Glass'],
  ['فشرده', 'Compact'],
  ['خطی', 'Outline'],
  ['کافه', 'Coffee'],
  ['ماچا', 'Matcha'],
  ['اقیانوس', 'Ocean'],
  ['بنفش', 'Violet'],
  ['شنی', 'Sand'],
  ['نعنا', 'Mint'],
  ['شبانه', 'Night'],
  ['مرجانی', 'Coral'],
  ['جنگلی', 'Forest'],
  ['آدامسی', 'Bubblegum'],
  ['لیمویی', 'Lemon'],
  ['فولادی', 'Steel'],
  ['سپیا', 'Sepia'],
  ['داده‌ها به‌صورت آفلاین در همین مرورگر ذخیره می‌شوند', 'Data is stored offline in this browser'],
  ['ذخیره‌سازی آفلاین روی همین دستگاه', 'offline storage on this device'],
  ['پلنر ', 'Planner '],
  ['پلنر', 'Planner'],
  ['دقیقه', 'min'],
  ['افزودن کار', 'Add task'],
  ['افزودن', 'Add'],
  ['نمای هفته', 'Week view'],
  ['نمای ماه', 'Month view'],
  ['رویداد سریع', 'Quick event'],
  ['زیردسته جدید...', 'New subcategory...'],
  ['زیردسته جدید', 'New subcategory'],
  ['ویرایش', 'Edit'],
  ['تصویر پلنر', 'Planner image'],
  ['تصویر', 'Image'],
  ['داشبورد', 'Dashboard'],
  ['هفتگی', 'weekly'],
  ['موردی ثبت نشده.', 'Nothing recorded.'],
  ['تولد', 'birthday'],
  ['دوستم', 'my friend'],
  ['ویتابین', 'vitamin'],
  ['ویتامین', 'vitamin'],
  ['زیراقدام', 'sub-action'],
  ['نمای', 'view'],
  ['امروز چه خبر بود؟', 'How was today?'],
  ['این هفته چطور بود؟ چه چیزی خوب پیش رفت؟', 'How was this week? What went well?'],
  ['انتقال به هفته بعد', 'Move to next week'],
  ['اقدام / زیراقدام جدید...', 'New action / sub-action...'],
  ['بدون عنوان', 'Untitled'],
  ['تمام‌شده', 'Finished'],
  ['عادتی ثبت نشده.', 'No habits yet.'],
  ['کارهای امروز', 'Today’s tasks'],
  ['ارزیابی روز', 'Day rating'],
  ['ارزیابی', 'Rating'],
  ['تاریخچه', 'History'],
  ['سلام', 'Hi'],
  ['زبان', 'Language'],
  ['رضا', 'Reza'],
  [' از ', ' of '],
  [' تا ', ' to '],
  ['<label>روز</label>', '<label>Day</label>'],
  ['روز ', 'Day '],
  [' روز', ' days'],
  ['روز', 'Day'],
  ['های', ''],
  ['اقدام', 'action'],
  ['ثبت', 'log'],
  ['جدید', 'new'],
  ['بدون', 'No'],
  ['بعد', 'next'],
  ['انتقال', 'Move'],
  ['تمام', 'Finished'],
  ['خبر', 'news'],
  ['خوب', 'good'],
  ['بود', 'was'],
  ['رفت', 'went'],
  ['چطور', 'how'],
  ['چه', 'what'],
  ['چیزی', 'anything'],
  ['پیش', 'forward'],
  ["+ 'س',", "+ 'h',"],
  ['ه</div>', 'k</div>'],
  ['weekly و Monthly', 'weekly & monthly'],
  ['مد نظرش', 'in mind'],
  ['حال و هوا (مود ترکر)', 'Mood tracker'],
  ['حال و هوا (مود)', 'Mood'],
  ['مود ترکر امروز', 'Today’s mood'],
  ['مود ۱۴ روز اخیر', 'Mood — last 14 days'],
  ['امروز چه حسی داشتی؟', 'How did you feel today?'],
  ['۳۰ روز اخیر — برای تیک‌زدن روی روز بزن', 'Last 30 days — tap a day to toggle'],
  ['۳۰ روز اخیر', 'Last 30 days'],
  ['فهرست پلنر', 'Planner menu'],
  ['ترتیب بخش‌ها را جابه‌جا کن یا هرکدام را مخفی کن', 'Reorder sections or hide any of them'],
  ['حالت نمایش', 'Appearance'],
  ['روشن یا تاریک', 'Light or dark'],
  ['روشن', 'Light'],
  ['تاریک', 'Dark'],
  ['نمایش', 'Show'],
  ['مخفی', 'Hide'],
  ['هدف / یادداشت این دسته (دلخواه)', 'Category goal / note (optional)'],
  ['هر موردی که مدنظرت هست اینجا بنویس...', 'Write anything you have in mind here...'],
  ['خیلی بد', 'Very bad'],
  ['معمولی', 'Okay'],
  ['عالی', 'Great'],
  ['متوسط', 'Medium'],
  ['بد', 'Bad'],
  ['خوب', 'Good'],
  ['و', '&']
];

const pairs = DIC.slice().sort(function (a, b) { return b[0].length - a[0].length; });
pairs.forEach(function (p) { app = app.split(p[0]).join(p[1]); });

// digits, percent, punctuation
const FA_D = '۰۱۲۳۴۵۶۷۸۹';
app = app.replace(/[۰-۹]/g, function (d) { return String(FA_D.indexOf(d)); });
app = app.split('٪').join('%');
app = app.split('،').join(',');
app = app.split('؛').join(';');
app = app.split('؟').join('?');

fs.writeFileSync(ROOT + '/js/app.en.js', app, 'utf8');

// leftover persian in code (comments stripped, so only real UI/string text remains)
const codeOnly = app.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
const left = codeOnly.match(/[\u0600-\u06FF]+/g) || [];
const uniq = [...new Set(left)].sort();
const report = uniq.map(function (t) {
  const idx = codeOnly.indexOf(t);
  return t + '  ||  ' + codeOnly.slice(Math.max(0, idx - 35), idx + t.length + 35).replace(/\s+/g, ' ');
}).join('\n');
fs.writeFileSync(TMP + '/leftover.txt', report, 'utf8');
console.log('app.en.js written. leftover persian tokens in code:', uniq.length);
if (uniq.length) {
  console.error('Translation incomplete. Add these to the DIC map in scripts/translate.js:');
  console.error(report);
  process.exitCode = 1;
}
